using System.Text;
using UnityCodeGen;
using UnityEditor;

[Generator]
public class AutoCollectSystemGenerator : ICodeGenerator
{
    public void Execute(GeneratorContext context)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Leopotam.EcsLite;");
        sb.AppendLine("public partial class AutoCollectSystem : AutoCollectSystemBase");
        sb.AppendLine("{");
        sb.AppendLine("public override void AddAutoCollectSystems(EcsSystems systems)");
        sb.AppendLine("{");

        var types = TypeCache.GetTypesWithAttribute<AutoCollectSystemAttribute>();
        foreach (var type in types)
        {
            var name = type.FullName;
            sb.AppendLine("systems.Add(new " + name + "());");
        }

        sb.AppendLine("}");
        sb.AppendLine("}");

        context.AddCode("AutoCollectSystem.Generated.cs", sb.ToString());
    }
}