using System.Reflection;
using System.Text;
using SevenBoldPencil.EasyEvents;
using UnityCodeGen;
using UnityEditor;
using UnityEngine;

[CreateAssetMenu(fileName = "UnityGeneratorSettings", menuName = "Moba World/UnityCodeGen/UnityGeneratorSettings")]
public class UnityGeneratorSettings : ScriptableObject
{
}

[Generator]
public class AutoCollectSystemGenerator : ICodeGenerator
{
    public void Execute(GeneratorContext context)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Leopotam.EcsLite;");
        sb.AppendLine("public partial class AutoCollectSystem : AutoCollectSystemBase");
        sb.AppendLine("{");
        sb.AppendLine("public override EcsSystems AddAutoCollectSystems(EcsSystems systems)");
        sb.AppendLine("{");

        var types = TypeCache.GetTypesWithAttribute<AutoCollectSystemAttribute>();
        foreach (var type in types)
        {
            var name = type.FullName;
            sb.AppendLine("systems.Add(new " + name + "());");
        }

        sb.AppendLine("return systems;");

        sb.AppendLine("}");
        sb.AppendLine("}");

        context.OverrideFolderPath(LeoEcsNetworkCodeGen.GetCodeGenPath());
        context.AddCode("AutoCollectSystem.Generated.cs", sb.ToString());
    }
}